# Demo code:
spring:
  datasource:
    username: root
    password: Lg123456
    url: jdbc:mysql://sh-cynosdbmysql-grp-5dm6we56.sql.tencentcdb.com:24026/schoolforum?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  elasticsearch:
    rest:
      uris: 110.40.156.29:9200
  mail:
    # Set up the SMTP server adress
    host: smtp.qq.com
    # Sender email adress with POP3/SMTP service access
    username: 1018554215@qq.com # Sender email with POP3/SMTP service available
    # Set up the password, which is the access code
    password: qptdeclxzsjubedj #Access code
    # Emailing suggestions to xxx 
    mailRecipient: wellcourse@163.com #email receiving suggestions
    # Port: 465 or 587（for @qq only port 587 is available）
    port: 587
    # Default encoding: UTF-8
    default-encoding: UTF-8
    # Set up the SSL authtoken_factory
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        # Open debug mode and sending the log
        debug: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
# mybatis-plus configuration
mybatis-plus:
  # xml file location
  mapper-locations: classpath:mapper/*.xml

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImp  l

logging:
  level:
    root: debug
  file:
    path: F:\\logs
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com   # End point location
    accessKeyId: LTAI5tByayajg8LBCwqD51qi  # keyID for user registration
    accessKeySecret: 24Y0cVETjH8bkAJkSrQ7wgCMYOfdI7   # Key token for registered user
    bucketName: schoolforum   # BucketName, e.g.：pictured-st
    key: schoolforum/     # key storage location